name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        pip-sphinx: [sphinx]
        include:
          - python-version: 3.9
            pip-sphinx: sphinx==2.1
          - python-version: 3.9
            pip-sphinx: --pre sphinx
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest codecov coverage
        python -m pip install ${{ matrix.pip-sphinx }}
        pip install .
    - name: Install extra dependencies
      run: |
        python -m pip install flake8 check-manifest mypy types-setuptools types-docutils
      if: matrix.pip-sphinx == 'sphinx' && matrix.python-version == '3.9'
    - name: Check manifest
      run: |
        check-manifest
      if: matrix.pip-sphinx == 'sphinx' && matrix.python-version == '3.9'
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source
        flake8 . --count --max-complexity=10
      if: matrix.pip-sphinx == 'sphinx' && matrix.python-version == '3.9'
    - name: Type checking with mypy
      run: mypy
      if: matrix.pip-sphinx == 'sphinx' && matrix.python-version == '3.9'
    - name: Documentation
      run: |
        pushd doc && make html && popd
      if: matrix.pip-sphinx == 'sphinx' && matrix.python-version == '3.9'
    - name: Test with pytest
      run: |
        coverage run -m pytest
        codecov
